### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by am2mcu** [am2mcu/DotinSession1#1]
- [ ] define **enum** for user_role column
- [ ] JWT token
- [ ] add real date to Room
- [ ] permitAll() endpoints do not load
